#!/usr/bin/env bash

# Author: Piotr Miller
# e-mail: nwg.piotr@gmail.com
# Website: http://nwg.pl
# Project: https://github.com/nwg-piotr/swayinfo
# License: GPL3

# Credits: https://github.com/dsboger/gnome-shell-extension-bumblebee-status

# Use in py3status as external_script module:

# external_script {
#     format = "{output}"
#     script_path = "path_to_the_script/bbswitch"
#     cache_timeout = 1
# }

if [[ -f "/proc/acpi/bbswitch" ]]; then

    bb_status=$(cat /proc/acpi/bbswitch | awk -F ' ' '{print $2}')

    if [[ "$bb_status" = "ON" ]]; then

        t=$(nvidia-smi -q -d TEMPERATURE | grep "GPU Current Temp" | awk -F ' ' '{ print $5 }')
        # Couldn't find a glyph to represent NVIDIA or bbswith; replace with whatever you like
        echo " ${t}℃"
    fi
else
    if [[ $1 == -N* ]]; then
            echo "BB?"
    fi
fi
