#!/bin/bash

# Shortened version of https://github.com/moverest/sway-interactive-screenshot
# w/o rofi, for use with key bindings

function list_geometry () {
	[ "$2" = with_description ] && local append="\t\(.name)" || local append=
	swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.'$1' and .pid) | "\(.rect.x),\(.rect.y) \(.rect.width)x\(.rect.height)'$append'"'
}

WINDOWS=`list_geometry visible with_description`
FOCUSED=`list_geometry focused`

CHOICE=$1

SAVEDIR=${SWAY_INTERACTIVE_SCREENSHOT_SAVEDIR:=~/Obrazy/Screenshots}
mkdir -p -- "$SAVEDIR"
FILENAME="$SAVEDIR/$(date +'%Y-%m-%d-%H%M%S_screenshot.png')"
EXPENDED_FILENAME="${FILENAME/#\~/$HOME}"

case $CHOICE in
    fullscreen)
        grim "$EXPENDED_FILENAME"
	;;
    region)
        grim -g "$(slurp)" "$EXPENDED_FILENAME"
	;;
    focused)
        grim -g "$FOCUSED" "$EXPENDED_FILENAME"
	;;
	display)
        grim -o $(swaymsg -t get_outputs | jq -r '.[] | select(.focused) | .name') "$EXPENDED_FILENAME"
	;;
esac

wl-copy < "$EXPENDED_FILENAME"
notify-send "Screenshot" "File saved as <i>'$FILENAME'</i> and copied to the clipboard." -i "$EXPENDED_FILENAME"